### ISSUE TITLE
VSCode sui-move-analyzer plugin problem

### ISSUE THREAD

**Issue by cyberpo9t** [move-language/move#1109]
When I use the sui-move-analyzer plugin in VSCode, I encountered the following issues:

```
parse manifest '"/home/user/.move/https___github_com_MystenLabs_sui_git_framework__testnet/crates/sui-framework/packages/sui-framework" 'failed.
 addr must exactly 32 length or start with '0x' like '0x2'
Error parsing '[package]' section of manifest

Caused by:
    Invalid 'edition'. Unsupported edition "2024.beta". Current supported editions include: "legacy", "2024.alpha"
```

My `Move.toml` :
```toml
[package]
name = "task1"

version = "1.0.0"
edition = "2024.alpha"
license = "MIT"
authors = ["Joe Smith (joesmith@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
task1 = "0x0"

[dev-dependencies]

[dev-addresses]
```

My VSCode `settings.json`:
```json
{
  "sui-move-analyzer.server.path": "~/.cargo/bin/sui-move-analyzer",
  "move-analyzer.server.path": "~/.cargo/bin/move-analyzer",
  "move.server.path": "~/.cargo/bin/move-analyzer"
}
```

The command executed during the installation of sui-move-analyzer is:
```bash
cargo install --git https://github.com/movebit/move --branch sui_move_analyzer sui-move-analyzer
```

I made some attempts to resolve this issue, and eventually, I found that installing sui-move-analyzer with another command, while keeping all configurations unchanged, solved the problem.
```bash
cargo install --git https://github.com/movebit/move --branch move-analyzer2 move-analyzer
```
By using this command to install move-analyzer and then renaming it to sui-move-analyzer, the issue was perfectly resolved.
So, is there a bug in the sui_move_analyzer branch?
